### ISSUE TITLE
Issue: Wrong color of types

### ISSUE THREAD

**Issue by yeysman** [catppuccin/vscode#455] opened 2024-11-11 21:13 UTC
Colors of standard types in struct defer from custom ones.
Please see the screenshot 

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/1e803004-e0d3-401b-9fae-63eaa9071470">

from the left side is VS code, from the right side - Zed editor, which looks much better.
Not sure, if it is really issue or it is just the way VS code colorize types.

**Comment by uncenter** [comment] 2024-11-11 23:24
Builtin types should ideally be mauve/keyword colored, so the VS Code behavior is actually preferred to that of Zed. A fix for Zed to make builtin types mauve is in the works.

**Comment by sgoudham** [comment] 2024-11-12 00:44
Hey 👋,
Thanks for letting us know about the discrepancy.

As mentioned above, this is intended behaviour and Zed has landed a PR to update the highlights to match VSCode here: https://github.com/catppuccin/zed/pull/44

I understand you may be disappointed by this outcome as you prefer Zed editor's screenshot. It may be worth looking into if Zed allows local overrides to syntax highlighting tokens so that you can keep all types to one colour as you prefer.

**Closed by sgoudham** 2024-11-12 00:44 UTC
