### ISSUE TITLE
The 'Catppuccin for VSCode' extension is not available in Visual Studio Code for the web.

### ISSUE THREAD

**Issue by birobirobiro** [catppuccin/vscode#82] opened 2023-01-06 17:43 UTC
When I try to install the Catppuccin theme extension for VS Code I come across this message and I can't install it

> The 'Catppuccin for VSCode' extension is not available in Visual Studio Code for the web. [know why](https://code.visualstudio.com/docs/editor/vscode-web#_extensions)

Link to test: https://github.dev/catppuccin/catppuccin

Preview error:

![image](https://user-images.githubusercontent.com/22185823/211068257-b25dfad3-618e-436f-b172-bcf85305f642.png)

**Comment by nekowinston** [comment] 2023-01-10 05:47
Hi there!

This is a duplicate of #74, I'd have to pre-compile the theme with default options, and disable all preferences since VSCode web doesn't support re-compiling themes AFAIK (at least the last time I checked).

**Closed by nekowinston** 2023-01-10 05:47 UTC
