### ISSUE TITLE
VS Code colours break

### ISSUE THREAD

**Issue by ale-dg** [catppuccin/vscode#97] opened 2023-04-06 23:47 UTC
Hi all,

I have been having an issue with the colours in VS Code. After a while of working, the colour scheme of the code is gone. I have noticed it is mostly with the oranges, i.e. the modules imported in Python (not sure EXACTLY to which VS keys are these configured to) and SOMETIMES happens when I scroll too fast (either up or down). I have reinstalled VS Code from scratch and only installing Catppuccin + Python packages (Catppuccin's version is 2.7.0),  but the issue remains. I am on MacOS. I leave you below a copy of the settings json, should it be helpful.

Thanks

Kind regards

`"[python]": {
        "editor.formatOnType": true
    },
    "workbench.colorTheme": "Catppuccin Mocha",
    "workbench.iconTheme": "catppuccin-mocha",
    "editor.cursorSmoothCaretAnimation": "explicit",
    "editor.cursorBlinking": "solid",
    "editor.fontFamily": "CascadiaCode-Regular",
    "editor.fontLigatures": "'calt', 'ss01', 'ss02', 'ss04', 'ss05', 'ss06', 'onum' 'zero'",
    "editor.fontSize": 16,
    "editor.wordWrap":"on",
    "notebook.output.fontSize": 16,
    "notebook.output.fontFamily": "CascadiaCode-Regular",
    "notebook.output.scrolling": true,
    "notebook.output.wordWrap": true,
    "diffEditor.wordWrap": "on",
    "workbench.preferredDarkColorTheme": "Catppuccin Mocha",
    "workbench.preferredLightColorTheme": "Catppuccin Latte",
    "workbench.editor.autoLockGroups": {
        "jupyter-notebook": true,
        "terminalEditor": true
    },
    "interactiveSession.editor.wordWrap": "on",
    "editor.semanticHighlighting.enabled": true,
    "workbench.fontAliasing": "auto",`

**Comment by ale-dg** [comment] 2023-04-07 01:25
Hi,

Just for completeness, I have looked into the theme's json and it points to entity.name.namespace

**Comment by ThomasJRyan** [comment] 2023-04-23 01:01
To on onto this, In 2.7.0 I'm also getting an error on Windows

![image](https://user-images.githubusercontent.com/18319621/233813757-5affadb8-c6ef-4b02-8269-2d5abf363809.png)

It seems the JSON files are empty for some reason

![image](https://user-images.githubusercontent.com/18319621/233813771-d3748b20-be4b-4170-96f0-0f6c022fc4e2.png)

For now, downgrading to 2.6.3 allows it to work again

**Comment by codeonblocks** [comment] 2023-05-18 22:53
I can also confirm that whenever I try to use the 'Extension Settings' of the extension it causes VS Code to freeze and break.

**Comment by nyxkrage** [comment] 2023-09-01 01:28
I cannot reproduce this on 2.9.0

**Comment by nekowinston** [comment] 2023-09-02 22:14
Closing this since I could never reproduce this & 3.0.0 just got released.

**Closed by nekowinston** 2023-09-02 22:14 UTC
Labels: cant-reproduce

**Comment by ale-dg** [comment] 2023-09-03 22:37
Hi,

I think it was an issue on VSCode since it also happened on other themes, I had raised an issue there and a lot of fellas also gave feedback there. It hasn't broken since the latest VSCode update though, but sometimes it takes time to load, especially when fast scrolling using Jupyter. Anyway, thank you for checking and trying to replicate. I'll raise a new issue should it happen again.

Best
