### ISSUE TITLE
Select flavor when installing from the marketplace

### ISSUE THREAD

**Issue by numpad** [catppuccin/vscode#34] opened 2022-08-10 10:04 UTC
Installing the Catppuccin color theme from one of the preferred installation methods does not provide me with an option to switch to "Latte" or other flavors.

I am using Visual Studio Code 1.70.0.

**Comment by yosiat** [comment] 2022-08-10 11:51
@numpad the new version isn't released yet to market, suggest to follow this issue (like I do) - https://github.com/catppuccin/vscode/issues/32

**Comment by numpad** [comment] 2022-08-12 06:54
That makes sense, thanks!

**Comment by nekowinston** [comment] 2022-08-16 12:36
Closing this as a duplicate of #32

**Closed by nekowinston** 2022-08-16 12:36 UTC
