### ISSUE TITLE
PHP Syntax highlighting issues

### ISSUE THREAD

**Issue by migueldamota** [catppuccin/vscode#186] opened 2023-10-06 09:31 UTC
Hi there, I found some issues for PHP:

1. Variables inside of a string don't look right. If it's intentional it's fine with me (it's just looking weird 😅)
<img width="196" alt="image" src="https://github.com/catppuccin/vscode/assets/55055484/829d965f-d82d-4a34-9fdf-92810770880f">

---

2. PHP built-in functions like `echo` or `isset` aren't highlighted differently as before (v2.9.0)

- Now
<img width="237" alt="image" src="https://github.com/catppuccin/vscode/assets/55055484/897a545e-4867-4dfa-af7f-70301f2a7a00">

- Before
<img width="232" alt="image" src="https://github.com/catppuccin/vscode/assets/55055484/67f516d7-5e5a-4aca-80df-c23ac3c3e1dd">

---

3. Opening and closing tag are inconsistent
<img width="88" alt="image" src="https://github.com/catppuccin/vscode/assets/55055484/02e71aa5-4e4e-4ec5-80ee-5fe6d5d837e2">

For me, these are minor issues but I just want to point them out 😄

Have a great day!

**Comment by nekowinston** [comment] 2023-10-06 09:41
Thanks for reporting those, I'll have a look at 1 & 3, but 2 seems intentional to me, as blue is used for functions elsewhere; which color would you expect there?

**Comment by migueldamota** [comment] 2023-10-06 10:01
Hi @nekowinston, thank you. For 2, I thought about a light blue (like before) because it's built-in and not a custom function

**Comment by nekowinston** [comment] 2023-10-21 11:49
1. Fixed with https://github.com/catppuccin/vscode/pull/190
2. Fixed with https://github.com/catppuccin/vscode/pull/193
3. I can't reproduce that one unless I have invalid Syntax, I can't tell what's happening for you from your `?><?php` snippet alone.

**Closed by nekowinston** 2023-10-21 11:49 UTC
Labels: bug

**Comment by migueldamota** [comment] 2023-10-21 12:23
Thank you so much!

For 3, I am always getting this when I close a php tag. I can only give you more screenshots but I don't know if this helps
