### ISSUE TITLE
inconsistent colors (vscode, nvim, bat)

### ISSUE THREAD

**Issue by AlexNabokikh** [catppuccin/vscode#100] opened 2023-04-16 08:14 UTC
Hello Catppuccin community,

I recently set Catppuccin Macchiato to VSCode, Nvim, and Bat, but for some reason, I am getting inconsistent colors in all of them.
What am I doing wrong?
![issue](https://user-images.githubusercontent.com/42908293/232284233-2faa53dd-7229-4be0-a62c-654767248549.png)

**Comment by codeonblocks** [comment] 2023-05-19 17:55
+1, not sure why all the colors are different if it's all the same theme.

**Comment by nekowinston** [comment] 2023-05-19 18:06
Duplicate of #62

explanation copied from #101:

> The underlying Syntax highlighting of this plugin hasn't changed in 9 months. (#24)
I've done some development on the plugin side of things, but personally don't use VSCode; I don't have much motivation to continue work on #53, and would be happy for someone else to continue to work on it.

**Closed by nekowinston** 2023-05-19 18:06 UTC
