### ISSUE TITLE
White/gray/black accent color

### ISSUE THREAD

**Issue by mattlucock** [catppuccin/vscode#410] opened 2024-07-12 04:56 UTC
The available options for configuring the accent color are all light shades of various hues from the Catppuccin palette, which makes sense. However for me, the accent color having any particular hue is visually distracting, and I would really prefer for it to just be light gray or white, given that I'm using a dark theme. If I were using the light theme, I imagine I would prefer it to be dark gray. For now I'm getting by with `rosewater`, which to my eye looks relatively close to white, but I would really prefer for it to just be light gray or white. I feel like these options would naturally fit alongside the existing options, but I'm keen to hear thoughts on this.

See also #411

**Comment by sgoudham** [comment] 2024-11-09 00:35
Closing this as a duplicate of #411 as any solution to this issue would be fulfilled in that one.

**Closed by sgoudham** 2024-11-09 00:35 UTC
