### ISSUE TITLE
Undercurl seems to be too high in latest VSCode version

### ISSUE THREAD

**Issue by aegonz** [catppuccin/vscode#373] opened 2024-04-17 12:50 UTC
Undercurl seems to be too high in latest VSCode version. This makes reading the word harder

VSCode:
```
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z (6 days ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

<img width="344" alt="Screenshot 2024-04-17 at 7 49 22 AM" src="https://github.com/catppuccin/vscode/assets/67929578/5963f20d-29d1-488a-bbbd-d8454d597266">

**Comment by nekowinston** [comment] 2024-04-17 12:52
Duplicate of #361

**Closed by nekowinston** 2024-04-17 12:52 UTC
