### ISSUE TITLE
Fails to build on NixOS

### ISSUE THREAD

**Issue by tylergets** [catppuccin/vscode#390] opened 2024-05-17 21:55 UTC
Hey there, I wanted to try out this theme and installed it to my Flake. The build seems to be failing due to an esbuild issue `Error: spawn ETXTBSY`

Build logs:
```@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/gjbwzygb01piyxsr2nbpaznp4mx4nkp2-vwqff6xv24vgk30pvw93kalv4b50g2ph-catppuccin-vsc-3.14.0
source root is vwqff6xv24vgk30pvw93kalv4b50g2ph-catppuccin-vsc-3.14.0
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 335ms
➤ YN0000: ┌ Link step
➤ YN0005: │ keytar@npm:7.9.0 lists build scripts, but its build has been explicitly disabled through configuration.
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.64 must be built because it never has been before or the last one failed
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR Error: spawn ETXTBSY
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ es5-ext@npm:0.10.64 STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ es5-ext@npm:0.10.64 couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-52899df9/build.log)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR Error: spawn ETXTBSY
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ esbuild@npm:0.19.12 couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-f493228f/build.log)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR Error: spawn ETXTBSY
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ esbuild@npm:0.19.12 STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ esbuild@npm:0.19.12 couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-9e63febe/build.log)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR Error: spawn ETXTBSY
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ esbuild@npm:0.18.20 STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-71e9a837/build.log)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR Error: spawn ETXTBSY
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ esbuild@npm:0.20.2 STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ esbuild@npm:0.20.2 couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-df7c4062/build.log)
➤ YN0007: │ @catppuccin/vscode-monorepo@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR Error: spawn ETXTBSY
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at ChildProcess.spawn (node:internal/child_process:421:11)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at Object.spawn (node:child_process:761:9)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at JY (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:9:52616)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at LE.implementation (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:159:1348)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at LE.exec (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1414)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at LE.run (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:1585)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at oce (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:165:7428)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at async Eot (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:16)
➤ YN0000: │ @catppuccin/vscode-monorepo@workspace:. STDERR     at async u (/nix/store/vz0jbszxc5lvqp418v3dc1gx1jfr10b5-yarn.js:167:147)
➤ YN0009: │ @catppuccin/vscode-monorepo@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /build/xfs-5e9c036c/build.log)
➤ YN0000: └ Completed in 2s 165ms
➤ YN0000: · Failed with errors in 2s 751ms
```

Any help would be appreciated!

**Comment by nekowinston** [comment] 2024-05-17 23:54
Hi, I can't replicate this locally or [via the CI](https://github.com/catppuccin/vscode/actions/runs/9135492366). 🤔 

Can you try the last release pushed to [FlakeHub](https://flakehub.com/flake/catppuccin/vscode)? (`https://flakehub.com/f/catppuccin/vscode/3.*.*.tar.gz`)

**Comment by reidlabwastaken** [comment] 2024-05-24 21:52
build failure on both `b7a8806f7532a091b0170f281dbc7f35c3fc7761`, also fails on `https://flakehub.com/f/catppuccin/vscode/3.14.0.tar.gz` (latest)

**Comment by Moonlight-Angel** [comment] 2024-05-25 10:07
I can also replicate this, once I updated the nixpkgs flake to the latest commit on `nixos-unstable`, so it seems that something in nixpkgs triggers errors when building this package.
I tried to investigate further but didn't find anything, unfortunately.

I think that once you'll update the nixpkgs flake in this repo, you'll be able to replicate the issue on the CI :thinking: 
And I think it fails on our side because we use `inputs.nixpkgs.follows = "nixpkgs";` on the `catppuccin-vsc` flake

**Comment by nekowinston** [comment] 2024-05-25 16:47
Going to reopen this issue since it seems to be a flaky build at the moment.

I quickly tried to fix it by reverting to `nodejs_18` in `nix/default.nix`, but this didn't help. Neither did upgrading all packages (I was hoping for a random fix upstream somewhere).

FYI, I recently retired from Catppuccin (https://github.com/catppuccin/catppuccin/pull/2402) so if you want to see Nix continued support for this repo, someone else would have to maintain it.

**Comment by reidlabwastaken** [comment] 2024-06-04 18:00
wow! seems to actually be a [kernel regression](https://lore.kernel.org/all/0ec1d936-ee3f-4df2-84df-51c15830091b@kernel.dk/)

**Comment by johannlejeune** [comment] 2024-06-09 08:49
I think that if you're having this error, you're already on kernel 6.9.1 (which is affected by the regression @reidlabwastaken talks about), which means you're basically trapped :joy: 
You need to update to a newer kernel version to be able to build the Catppuccin theme again, but in order to update, you need to temporarily comment out that Catppuccin theme, that's what I ended up doing.
Once you reboot into a newer kernel version (for me it was 6.9.3), you'll be able to build everything again :+1:

**Comment by sgoudham** [comment] 2024-08-02 16:33
I'm going to close this since it's not relevant to the extension and I don't think we can do anything on our end. Feel free to re-open if there is.

**Closed by sgoudham** 2024-08-02 16:33 UTC
